spring:
  cloud:
    gateway:
      routes:
        ## service1
        - id: eureka-server-test
          uri: lb://eureka-server-test
          predicates:
            - Path=/eureka-server-test/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1